### ISSUE TITLE
RuntimeError: leaf variable has been moved into the graph interior

### ISSUE THREAD

**Issue by mansoor49** [Alex-Fabbri/lang2logic-PyTorch#1]
Hi,

While running 
enc_outputs = torch.zeros((enc_batch.size(0), enc_max_len, encoder.hidden_size), requires_grad=False)

it gives error:
RuntimeError: leaf variable has been moved into the graph interior

**Comment by Alex-Fabbri** [comment]
Hi @mansoor49 

Can you provide more info on your environment (what Python, torch versions etc)? I do not encounter that error with Python 3.6.2 and PyTorch 0.4.1

**Comment by mansoor49** [comment]
While running main.py in Spider, in the function eval_training I encountered the error in following lines:

enc_outputs = torch.zeros((enc_batch.size(0), enc_max_len, encoder.hidden_size), requires_grad=True)
enc_s[0][i] = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)
dec_s[0][i] = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)

and corrected following lines by cloning: 

    xa = torch.zeros((enc_batch.size(0), enc_max_len, encoder.hidden_size), requires_grad=True)
    enc_outputs = xa.clone()
    xb = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)
    xc = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)
    enc_s[0][i] = xb.clone()
     dec_s[0][i] = xc.clone()

**Comment by reBiocoder** [comment]
> While running main.py in Spider, in the function eval_training I encountered the error in following lines:
> 
> enc_outputs = torch.zeros((enc_batch.size(0), enc_max_len, encoder.hidden_size), requires_grad=True) enc_s[0][i] = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True) dec_s[0][i] = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)
> 
> and corrected following lines by cloning:
> 
> ```
> xa = torch.zeros((enc_batch.size(0), enc_max_len, encoder.hidden_size), requires_grad=True)
> enc_outputs = xa.clone()
> xb = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)
> xc = torch.zeros((opt.batch_size, opt.rnn_size), dtype=torch.float, requires_grad=True)
> enc_s[0][i] = xb.clone()
>  dec_s[0][i] = xc.clone()
> ```

Has this problem been solved?
