### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by mansoor49** [Alex-Fabbri/lang2logic-PyTorch#2]
For seq2seq, I got following accuracies (based on Atis dataset):  

seq2seq (with attention) | Accuracy | 86.3839 | 84.2000
seq2seq (lstm) | Accuracy | 77.4554 | 75.7000

86.3839 is from py code whereas 84.2 is mentioned in the paper (lua code). Similarly, 77.4554 based on py code and 75.7 mentioned in the paper. 

On Geoqueries, I have following:

seq2seq (with attention) | Accuracy | 83.5714 | 84.6000
seq2seq (lstm) | Accuracy | 73.9285 | 72.9000

I am trying to understand the reason for having better accuracy in py code.

**Comment by Alex-Fabbri** [comment]
I think the discrepancies in accuracy result from differences in seed/random number initialization or CUDA version/hardware rather than any fundamental differences in the implementation.

**Comment by mansoor49** [comment]
I am running the code on CPU i.e. -1. 

So, yeah. I agree it can be from seed/random initialisation.

**Comment by mansoor49** [comment]
Hi, a question: with random seed initialisation, evaluation is normally taken as average results for n rounds. With the accuracy calculations in util.py, I believe this is not the case. 

Please confirm.

**Comment by Alex-Fabbri** [comment]
Seeds are set according to the seed parameter in main.py, although even with that variations in version and hardware can cause differences. You are right that evaluation of results is taken over a single round. For an overview of some of the problems with reproducibility I definitely recommend [this paper.](https://www.mitpressjournals.org/doi/pdf/10.1162/tacl_a_00018)

**Comment by mansoor49** [comment]
Thank you.
