### ISSUE TITLE
can the seq2tree do the batch training in decoding?

### ISSUE THREAD

**Issue by zhuang-li** [Alex-Fabbri/lang2logic-PyTorch#4]
Hi 

This pytorch version of seq2tree is amazing. 

I just wonder, in the original implementation, are instances of logic forms fed one by one into the decoder or as a single batch? As from my perspective, it is difficult to make it batch feeding as the decoder is a tree structure. I am doing some similar research and I want to see if I can make my implementation faster.

Best

Zhuang Li

**Comment by Alex-Fabbri** [comment]
Hi Zhuang, 

The original code also iterates over the batch, as seen [here](https://github.com/donglixp/lang2logic/blob/master/seq2tree/geoqueries/lstm/main.lua#L243). As you said, parallelization of such structures is difficult. Let me know if you have any additional questions. 

Best, 
Alex

**Comment by zhuang-li** [comment]
Thank you! I think I will find some alternative ways to make my implementation faster.
