### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by qizhust** [Alex-Fabbri/lang2logic-PyTorch#5]
Hi, thanks for the repo! I run the code with attention using the default seed, but get the following results
| model | dataset | accuracy |
|-------------|---------------|-------------|
| seq2tree | jobqueries| 0.85|
|seq2seq | jobqueries | 0.87|
|seq2tree | atis      |      0.79|
|seq2seq | atis     |        0.85|

The seq2seq model keeps winning the seq2tree, do you have any suggestion for this?

**Comment by Alex-Fabbri** [comment]
Hi, thank you for your interest! Unfortunately, I am no longer maintaining this and am unsure why the performance is worse. I would check out more recent papers, such as [those listed on paperswithcode](https://paperswithcode.com/sota/semantic-parsing-on-atis), which have much-improved performance.

**Comment by qizhust** [comment]
Thanks a lot! @Alex-Fabbri  I was just surprised by the relative performance of seq2seq and seq2tree.

**Comment by Alex-Fabbri** [comment]
Right, I don't recall the exact performance we got when we ran this at the time. I'm going to close this issue for now, but if you or anyone else finds any improvements or has other questions, feel free to follow up!
